/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


public class dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard.class.getName());

    public dashboard() {
        initComponents();
        jButton_RefreshActionPerformed(null); // Automatically loads students from DB on startup
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField_IDnumber = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jComboBox_gender = new javax.swing.JComboBox<>();
        jComboBox_course = new javax.swing.JComboBox<>();
        jComboBox_year = new javax.swing.JComboBox<>();
        jLabel_IDnum = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_gender = new javax.swing.JLabel();
        jLabel_course = new javax.swing.JLabel();
        jLabel_yearlevel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton_Clear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_SearchStudent = new javax.swing.JTextField();
        jButton_Search = new javax.swing.JButton();
        jButton_Refresh = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_StudentInformation = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton_UpdateStudent = new javax.swing.JButton();
        jButton_DeleteStudent = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton_AddNewStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT INFORMATION SYSTEM");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel_background.setBackground(new java.awt.Color(225, 208, 179));
        jPanel_background.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(112, 59, 59));

        jLabel1.setFont(new java.awt.Font("Raanana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("STUDENT INFORMATION SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("PT Serif", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(161, 141, 109));

        jPanel3.setBackground(new java.awt.Color(155, 180, 192));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 59, 59), 4));

        jTextField_IDnumber.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N

        jTextField_name.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N

        jTextField_email.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N

        jComboBox_gender.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jComboBox_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        jComboBox_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_genderActionPerformed(evt);
            }
        });

        jComboBox_course.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jComboBox_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Information Technology", "Data Science", "Technology and Communication Management" }));

        jComboBox_year.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jComboBox_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year ", "2nd Year", "3rd Year", "4th Year " }));

        jLabel_IDnum.setFont(new java.awt.Font("PT Serif", 1, 13)); // NOI18N
        jLabel_IDnum.setText("ID Number");

        jLabel_name.setFont(new java.awt.Font("PT Serif", 1, 13)); // NOI18N
        jLabel_name.setText("Name");

        jLabel_email.setFont(new java.awt.Font("PT Serif", 1, 13)); // NOI18N
        jLabel_email.setText("Email");

        jLabel_gender.setFont(new java.awt.Font("PT Serif", 1, 13)); // NOI18N
        jLabel_gender.setText("Gender");

        jLabel_course.setFont(new java.awt.Font("PT Serif", 1, 13)); // NOI18N
        jLabel_course.setText("Course");

        jLabel_yearlevel.setFont(new java.awt.Font("PT Serif", 1, 13)); // NOI18N
        jLabel_yearlevel.setText("Year Level");

        jLabel8.setFont(new java.awt.Font("Raanana", 1, 24)); // NOI18N
        jLabel8.setText("STUDENT CREDENTIALS");

        jButton_Clear.setBackground(new java.awt.Color(163, 72, 90));
        jButton_Clear.setFont(new java.awt.Font("Raanana", 1, 14)); // NOI18N
        jButton_Clear.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Clear.setText("CLEAR");
        jButton_Clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(132, 42, 59), 2));
        jButton_Clear.setOpaque(true);
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_IDnum, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_email, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_course, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_yearlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField_name)
                                        .addComponent(jTextField_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox_gender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox_year, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_IDnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel8)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_IDnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_IDnum))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_name))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_email))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_gender))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_course))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_yearlevel))
                .addGap(43, 43, 43)
                .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(155, 180, 192));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 59, 59), 4));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 59, 59), 2));

        jLabel9.setFont(new java.awt.Font("PT Serif", 1, 14)); // NOI18N
        jLabel9.setText("Search ");

        jTextField_SearchStudent.setFont(new java.awt.Font("PT Serif", 1, 14)); // NOI18N
        jTextField_SearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchStudentActionPerformed(evt);
            }
        });

        jButton_Search.setBackground(new java.awt.Color(225, 208, 179));
        jButton_Search.setFont(new java.awt.Font("PT Serif", 1, 14)); // NOI18N
        jButton_Search.setText("Search");
        jButton_Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(161, 141, 109)));
        jButton_Search.setOpaque(true);
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        jButton_Refresh.setBackground(new java.awt.Color(144, 171, 139));
        jButton_Refresh.setFont(new java.awt.Font("PT Serif", 1, 14)); // NOI18N
        jButton_Refresh.setText("Refresh");
        jButton_Refresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 120, 99)));
        jButton_Refresh.setOpaque(true);
        jButton_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_SearchStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_SearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Search)
                    .addComponent(jButton_Refresh))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Raanana", 1, 24)); // NOI18N
        jLabel11.setText("STUDENT INFORMATION");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 73, 83), 4));

        jTable_StudentInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Number", "Name", "Email", "Gender", "Course", "Year Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_StudentInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_StudentInformationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_StudentInformation);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_UpdateStudent.setBackground(new java.awt.Color(33, 52, 72));
        jButton_UpdateStudent.setFont(new java.awt.Font("Raanana", 1, 18)); // NOI18N
        jButton_UpdateStudent.setForeground(new java.awt.Color(148, 180, 193));
        jButton_UpdateStudent.setText("Update Student");
        jButton_UpdateStudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 119, 146), 2));
        jButton_UpdateStudent.setOpaque(true);
        jButton_UpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateStudentActionPerformed(evt);
            }
        });

        jButton_DeleteStudent.setBackground(new java.awt.Color(102, 34, 34));
        jButton_DeleteStudent.setFont(new java.awt.Font("Raanana", 1, 18)); // NOI18N
        jButton_DeleteStudent.setForeground(new java.awt.Color(255, 102, 102));
        jButton_DeleteStudent.setText("Delete Student");
        jButton_DeleteStudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(163, 72, 90), 2));
        jButton_DeleteStudent.setOpaque(true);
        jButton_DeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteStudentActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Raanana", 1, 18)); // NOI18N
        jLabel10.setText("Actions:");

        jButton_AddNewStudent.setBackground(new java.awt.Color(90, 120, 99));
        jButton_AddNewStudent.setFont(new java.awt.Font("Raanana", 1, 18)); // NOI18N
        jButton_AddNewStudent.setForeground(new java.awt.Color(235, 244, 221));
        jButton_AddNewStudent.setText("Add New Student");
        jButton_AddNewStudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 171, 139), 2));
        jButton_AddNewStudent.setOpaque(true);
        jButton_AddNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddNewStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_AddNewStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_UpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_DeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_DeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_UpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton_AddNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student", jPanel2);

        javax.swing.GroupLayout jPanel_backgroundLayout = new javax.swing.GroupLayout(jPanel_background);
        jPanel_background.setLayout(jPanel_backgroundLayout);
        jPanel_backgroundLayout.setHorizontalGroup(
            jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel_backgroundLayout.setVerticalGroup(
            jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_backgroundLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Student");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean validateInputs() {
        
        String id = jTextField_IDnumber.getText().trim();
        String name = jTextField_name.getText().trim();
        String email = jTextField_email.getText().trim();

        // Check for empty fields
        if (id.isEmpty() || name.isEmpty() || email.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill out all required fields (ID, Name, and Email).", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Check ID length (must be at least 10 characters/numbers)
        if (id.length() < 10) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid ID Number: Must be at least 10 characters long.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    private void jComboBox_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_genderActionPerformed

    private void jTextField_SearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchStudentActionPerformed

    private void jButton_UpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateStudentActionPerformed
        if (validateInputs()) {
            Model.Student stu = new Model.Student(
            jTextField_IDnumber.getText(), jTextField_name.getText(), jTextField_email.getText(),
            jComboBox_gender.getSelectedItem().toString(), jComboBox_course.getSelectedItem().toString(),
            jComboBox_year.getSelectedItem().toString()
            );
            new DAO.StudentDAO().updateStudent(stu);
            jButton_RefreshActionPerformed(null);
        }
    }//GEN-LAST:event_jButton_UpdateStudentActionPerformed

    private void jButton_AddNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddNewStudentActionPerformed
        
        String name = jTextField_name.getText().trim();
        
        if (validateInputs()) {
            
            DAO.StudentDAO dao = new DAO.StudentDAO();
            if (dao.isNameDuplicate(name)) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error: A student with the name '" + name + "' already exists.", 
                    "Duplicate Entry", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return; // Stop the process so the student isn't added
            }
            
            Model.Student stu = new Model.Student(
                jTextField_IDnumber.getText(), jTextField_name.getText(), jTextField_email.getText(),
                jComboBox_gender.getSelectedItem().toString(), jComboBox_course.getSelectedItem().toString(),
                jComboBox_year.getSelectedItem().toString()
            );
            dao.insertStudent(stu);
            jButton_RefreshActionPerformed(null);
            javax.swing.JOptionPane.showMessageDialog(this, "Student added successfully!");
        }
    }//GEN-LAST:event_jButton_AddNewStudentActionPerformed

    private void jButton_DeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteStudentActionPerformed
        String id = jTextField_IDnumber.getText();
        if(!id.isEmpty()){
            new DAO.StudentDAO().deleteStudent(id);
            jButton_RefreshActionPerformed(null);
            jButton_ClearActionPerformed(null);
        } else {
        // Simple popup message when no ID is found in the text field
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Please select a student from the table to delete.", 
            "No Selection", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_DeleteStudentActionPerformed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        // READ and SEARCH
        String query = jTextField_SearchStudent.getText();
        if (query.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a search term.", "Search Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        jTable_StudentInformation.setModel(new DAO.StudentDAO().searchStudents(query));
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jButton_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshActionPerformed
        // READ
        jTable_StudentInformation.setModel(new DAO.StudentDAO().searchStudents(""));
    }//GEN-LAST:event_jButton_RefreshActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        jTextField_IDnumber.setText("");
        jTextField_name.setText("");
        jTextField_email.setText("");
        jComboBox_gender.setSelectedIndex(0);
        jComboBox_course.setSelectedIndex(0);
        jComboBox_year.setSelectedIndex(0);
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jTable_StudentInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_StudentInformationMouseClicked
        
        // READ
        int row = jTable_StudentInformation.getSelectedRow();
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)jTable_StudentInformation.getModel();

        jTextField_IDnumber.setText(model.getValueAt(row, 0).toString());
        jTextField_name.setText(model.getValueAt(row, 1).toString());
        jTextField_email.setText(model.getValueAt(row, 2).toString());
        jComboBox_gender.setSelectedItem(model.getValueAt(row, 3).toString());
        jComboBox_course.setSelectedItem(model.getValueAt(row, 4).toString());
        jComboBox_year.setSelectedItem(model.getValueAt(row, 5).toString());
    }//GEN-LAST:event_jTable_StudentInformationMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddNewStudent;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_DeleteStudent;
    private javax.swing.JButton jButton_Refresh;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_UpdateStudent;
    private javax.swing.JComboBox<String> jComboBox_course;
    private javax.swing.JComboBox<String> jComboBox_gender;
    private javax.swing.JComboBox<String> jComboBox_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_IDnum;
    private javax.swing.JLabel jLabel_course;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_gender;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_yearlevel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_StudentInformation;
    private javax.swing.JTextField jTextField_IDnumber;
    private javax.swing.JTextField jTextField_SearchStudent;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_name;
    // End of variables declaration//GEN-END:variables
}
